# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Crossing Comm. Ave
tagline:             "Alex Wong's blog."
description:         ''
url:                 http://alexwong.me
baseurl:             'http://alexwong.me/blog'
paginate:            5

# About/contact
author:
  name:              Alex Wong
  url:               https://twitter.com/alexjwong
  email:

# Custom vars
version:             1.0.0
